version: '3.8'
services:
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    depends_on:
      - postgres_db
    ports:
      - ${ADMINER_PORT}:8080
